---

- name: Restart timesync
  ansible.builtin.systemd:
    state: restarted
    name: systemd-timesyncd
  become: true
  tags:
    - ntp
    - provision

- name: Reboot Ubuntu server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
    pre_reboot_delay: 15
    test_command: whoami
  become: true

- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true
